import { 
  Bot, 
  Globe, 
  Database, 
  Mail, 
  Clock, 
  Send, 
  Code, 
  FileText, 
  Check, 
  ChevronRight, 
  Menu, 
  X, 
  Save, 
  Undo, 
  Redo, 
  Play, 
  Settings, 
  Plus, 
  Copy, 
  Info, 
  ChevronDown,
  ArrowUp,
  ArrowDown,
  Minus,
  Shield,
  Bolt,
  LineChart,
  Users,
  Lightbulb,
  BarChart2,
  Search,
  LayoutGrid,
  List,
  ShoppingCart,
  ArrowLeftRight,
  ArrowLeft,
  ArrowRight,
  Share,
  Trash,
  UserPlus,
  ActivitySquare,
  Zap,
  GraduationCap,
  ArrowUpDown,
  RefreshCw,
  Boxes,
  SlidersHorizontal,
  Quote,
  Download,
  Calendar,
  Key,
  Phone,
  MessageSquare
} from "lucide-react";

// Import social media icons from react-icons
import { 
  FaTwitter, 
  FaLinkedin, 
  FaFacebook, 
  FaGithub, 
  FaStar, 
  FaStarHalfAlt,
  FaPuzzlePiece,
  FaTasks,
  FaCode,
  FaSyncAlt,
  FaRegWindowMaximize,
  FaGraduationCap,
  FaLayerGroup,
  FaNetworkWired,
  FaSitemap,
  FaBolt
} from "react-icons/fa";

// Icon mapping
export const Icons = {
  // App icons
  robot: Bot,
  globe: Globe,
  database: Database,
  email: Mail,
  clock: Clock,
  paperPlane: Send,
  code: Code,
  file: FileText,
  check: Check,
  chevronRight: ChevronRight,
  menu: Menu,
  close: X,
  save: Save,
  undo: Undo,
  redo: Redo,
  play: Play,
  settings: Settings,
  plus: Plus,
  copy: Copy,
  info: Info,
  chevronDown: ChevronDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  minus: Minus,
  shield: Shield,
  bolt: Bolt,
  chart: LineChart,
  users: Users,
  lightbulb: Lightbulb,
  barChart: BarChart2,
  search: Search,
  grid: LayoutGrid,
  list: List,
  puzzle: FaPuzzlePiece,
  
  // Additional icons for UI components
  x: X,
  shoppingCart: ShoppingCart,
  layoutGrid: LayoutGrid,
  arrowLeftRight: ArrowLeftRight,
  layoutTemplate: FaLayerGroup,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  workflow: FaSitemap,
  share: Share,
  trash: Trash,
  formInput: FaCode,
  userPlus: UserPlus,
  mail: Mail,
  send: Send,
  listTodo: FaTasks,
  gitBranch: FaNetworkWired,
  arrowDownUp: ArrowUpDown,
  refresh: RefreshCw,
  activity: ActivitySquare,
  plugZap: FaBolt,
  graduationCap: GraduationCap,
  appWindow: FaRegWindowMaximize,
  
  // Icons for pricing page
  sliders: SlidersHorizontal,
  quote: Quote,
  download: Download,
  calendar: Calendar,
  key: Key,
  phone: Phone,
  chat: MessageSquare,
  
  // Social media
  twitter: FaTwitter,
  linkedin: FaLinkedin,
  facebook: FaFacebook,
  github: FaGithub,
  
  // Rating
  star: FaStar,
  starHalf: FaStarHalfAlt
};